# Generated by Django 4.1.3 on 2022-11-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metiers', models.CharField(choices=[('TIC', 'tic'), ('MA', 'ma')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('heuredebut', models.TimeField()),
                ('heurefin', models.TimeField()),
                ('promo', models.CharField(max_length=300)),
                ('Annee', models.DateField()),
                ('Semaine', models.CharField(max_length=300)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isep.cour')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isep.filiere')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isep.formateur')),
                ('salls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isep.salle')),
            ],
        ),
    ]
