# Generated by Django 4.1.3 on 2022-11-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0003_alter_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='Annee',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
