# Generated by Django 4.1.3 on 2022-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0004_alter_planning_annee_alter_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(),
        ),
    ]
