# Generated by Django 4.1.3 on 2022-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0007_fillieremetier_remove_planning_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillieremetier',
            name='filiere',
        ),
        migrations.AddField(
            model_name='fillieremetier',
            name='Libelle',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='fillieremetier',
            name='metier',
            field=models.CharField(choices=[('TIC', 'tic'), ('MA', 'ma')], max_length=200, null=True),
        ),
    ]
