# Generated by Django 4.1.3 on 2022-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0008_remove_fillieremetier_filiere_fillieremetier_libelle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cour',
            old_name='Libelle',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='Libelle',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='fillieremetier',
            old_name='Libelle',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='Libelle',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='fillieremetier',
            name='planning',
        ),
        migrations.AddField(
            model_name='fillieremetier',
            name='planning',
            field=models.ManyToManyField(to='isep.planning'),
        ),
    ]
