# Generated by Django 4.1.3 on 2022-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0009_rename_libelle_cour_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semaine',
            name='filiereMetiers',
        ),
        migrations.AddField(
            model_name='semaine',
            name='filiereMetier',
            field=models.ManyToManyField(to='isep.fillieremetier'),
        ),
    ]
