# Generated by Django 4.1.3 on 2022-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isep', '0010_remove_semaine_filieremetiers_semaine_filieremetier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='activite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='filiere',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='formateur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
